name: Linter

on:
  pull_request:
    branches: [main, staging]

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  linter-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Latest
        uses: actions/checkout@v3
      - name: Install Deps
        run: npm install --legacy-peer-deps
      - name: Run Linter
        run: npm run lint
